import {
  Nigeria,
  Kenya,
  SouthAfrica,
  Uganda,
  Tanzania,
  Algeria,
  Ethiopia,
  Albania,
  Andorra,
} from "@/assets/flags";

export const supportedCountries = [
  {
    name: "Nigeria",
    currency: "NGN",
    symbol: "₦",
    basic: {
      price: "₦15,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "₦50,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$500",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Nigeria,
  },
  {
    name: "Kenya",
    currency: "KES",
    symbol: "Sh",
    basic: {
      price: "Sh950",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "Sh21,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$1,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Kenya,
  },
  {
    name: "South Africa",
    currency: "ZAR",
    symbol: "R",
    basic: {
      price: "R1,500",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "R2,500",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$1,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: SouthAfrica,
  },
  {
    name: "Delaware",
    currency: "USD",
    symbol: "$",
    basic: {
      price: "$400",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "$420",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$700",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Nigeria,
  },
  {
    name: "Ghana",
    currency: "GHS",
    symbol: "₵",
    basic: {
      price: "₵200",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "₵1,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$3,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Nigeria,
  },
  {
    name: "Uganda",
    currency: "UGX",
    symbol: "Sh",
    basic: {
      price: "Sh24,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "Sh1,500,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$1,500",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Uganda,
  },
  {
    name: "Tanzania",
    currency: "TZS",
    symbol: "Sh",
    basic: {
      price: "Sh1,000,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "Sh2,000,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$2,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Tanzania,
  },
  {
    name: "Rwanda",
    currency: "RWF",
    symbol: "Fr",
    basic: {
      price: "Fr150,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "Fr200,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$800",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Nigeria,
  },
  {
    name: "Zambia" /**/,
    currency: "ZMW",
    symbol: "ZK",
    basic: {
      price: "ZK150,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "ZK200,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$800",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Nigeria,
  },
  {
    name: "Ivory Coast (Côte d'Ivoire)",
    currency: "XOF",
    symbol: "Fr",
    basic: {
      price: "Fr100,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "Fr600,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$2,500",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Nigeria,
  },
  {
    name: "Senegal",
    currency: "XOF",
    symbol: "Fr",
    basic: {
      price: "Fr100,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "Fr600,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$2,200",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Nigeria,
  },
  {
    name: "Democratic Republic of Congo",
    currency: "XAF",
    symbol: "Fr",
    basic: {
      price: "Fr3,000,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "$2,500",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$3,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Nigeria,
  },
  {
    name: "Algeria",
    currency: "DZD",
    symbol: "د.ج",
    basic: {
      price: "د.ج250,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "د.ج300,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$3,500",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Algeria,
  },
  {
    name: "Angola",
    currency: "AOA",
    symbol: "Kz",
    basic: {
      price: "Kz70,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "Kz350,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$1,500",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Nigeria,
  },
  {
    name: "Ethiopia",
    currency: "ETB",
    symbol: "Br",
    basic: {
      price: "Br100,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "Br200,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$3,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Ethiopia,
  },
  {
    name: "Malawi",
    currency: "MWK",
    symbol: "MK",
    basic: {
      price: "MK20,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    pro: {
      price: "MK650,000",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    premium: {
      price: "$1,500",
      regTimeline: "3 Days",
      bankTimeline: "3 Days",
      taxTimeline: "3 Days",
    },
    flag: Nigeria,
  },
];
